eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8084/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: springcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/666wg/config.git
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"