server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8084/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: springcloud-zipkin

  security:
    user:
      name: admin
      password: admin

management:
  metrics:
    web:
      server:
        #zipkin报错无法访问，加此配置
        auto-time-requests: false

