eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8084/eureka
    register-with-eureka: false
  server:
    enable-self-preservation: false
spring:
  application:
    name: springcloud-eureka
server:
  port: 8084