eureka:
  client:
    service-url:
      defaultZone: http://${spring.cloud.client.ip-address}:${server.port}/eureka
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

spring:
  application:
    name: springcloud-eureka
  security:
    user:
      name: admin
      password: admin

server:
  port: 8084